//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetOborudovania.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        public int idOborudovania { get; set; }
        public byte[] foto { get; set; }
        public string seriyniyNomer { get; set; }
        public string naimenovanie { get; set; }
        public string opisanie { get; set; }
        public int nomerKabineta { get; set; }
        public string status { get; set; }
        public int idSotrudnika { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
