//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchetOborudovania.BaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RucovoditelyOfSotrudniki
    {
        public int idSvazi { get; set; }
        public int idSotrudnika { get; set; }
        public int idRucovoditela { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
